/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Get2ListsIdFollowersResponseMeta
 */
public class Get2ListsIdFollowersResponseMetaTest {
    private final Get2ListsIdFollowersResponseMeta model = new Get2ListsIdFollowersResponseMeta();

    /**
     * Model tests for Get2ListsIdFollowersResponseMeta
     */
    @Test
    public void testGet2ListsIdFollowersResponseMeta() {
        // TODO: test Get2ListsIdFollowersResponseMeta
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'previousToken'
     */
    @Test
    public void previousTokenTest() {
        // TODO: test previousToken
    }

    /**
     * Test the property 'resultCount'
     */
    @Test
    public void resultCountTest() {
        // TODO: test resultCount
    }

}
