/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Get2TweetsCountsAllResponseMeta
 */
public class Get2TweetsCountsAllResponseMetaTest {
    private final Get2TweetsCountsAllResponseMeta model = new Get2TweetsCountsAllResponseMeta();

    /**
     * Model tests for Get2TweetsCountsAllResponseMeta
     */
    @Test
    public void testGet2TweetsCountsAllResponseMeta() {
        // TODO: test Get2TweetsCountsAllResponseMeta
    }

    /**
     * Test the property 'newestId'
     */
    @Test
    public void newestIdTest() {
        // TODO: test newestId
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'oldestId'
     */
    @Test
    public void oldestIdTest() {
        // TODO: test oldestId
    }

    /**
     * Test the property 'totalTweetCount'
     */
    @Test
    public void totalTweetCountTest() {
        // TODO: test totalTweetCount
    }

}
