/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ResourceUnavailableProblemAllOf
 */
public class ResourceUnavailableProblemAllOfTest {
    private final ResourceUnavailableProblemAllOf model = new ResourceUnavailableProblemAllOf();

    /**
     * Model tests for ResourceUnavailableProblemAllOf
     */
    @Test
    public void testResourceUnavailableProblemAllOf() {
        // TODO: test ResourceUnavailableProblemAllOf
    }

    /**
     * Test the property 'parameter'
     */
    @Test
    public void parameterTest() {
        // TODO: test parameter
    }

    /**
     * Test the property 'resourceId'
     */
    @Test
    public void resourceIdTest() {
        // TODO: test resourceId
    }

    /**
     * Test the property 'resourceType'
     */
    @Test
    public void resourceTypeTest() {
        // TODO: test resourceType
    }

}
