/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.RulesRequestSummary;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RulesResponseMetadata
 */
public class RulesResponseMetadataTest {
    private final RulesResponseMetadata model = new RulesResponseMetadata();

    /**
     * Model tests for RulesResponseMetadata
     */
    @Test
    public void testRulesResponseMetadata() {
        // TODO: test RulesResponseMetadata
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'resultCount'
     */
    @Test
    public void resultCountTest() {
        // TODO: test resultCount
    }

    /**
     * Test the property 'sent'
     */
    @Test
    public void sentTest() {
        // TODO: test sent
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

}
