/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.TweetComplianceSchemaTweet;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetNotice
 */
public class TweetNoticeTest {
    private final TweetNotice model = new TweetNotice();

    /**
     * Model tests for TweetNotice
     */
    @Test
    public void testTweetNotice() {
        // TODO: test TweetNotice
    }

    /**
     * Test the property 'application'
     */
    @Test
    public void applicationTest() {
        // TODO: test application
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'eventAt'
     */
    @Test
    public void eventAtTest() {
        // TODO: test eventAt
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'extendedDetailsUrl'
     */
    @Test
    public void extendedDetailsUrlTest() {
        // TODO: test extendedDetailsUrl
    }

    /**
     * Test the property 'labelTitle'
     */
    @Test
    public void labelTitleTest() {
        // TODO: test labelTitle
    }

    /**
     * Test the property 'tweet'
     */
    @Test
    public void tweetTest() {
        // TODO: test tweet
    }

}
