/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetPublicMetrics
 */
public class TweetPublicMetricsTest {
    private final TweetPublicMetrics model = new TweetPublicMetrics();

    /**
     * Model tests for TweetPublicMetrics
     */
    @Test
    public void testTweetPublicMetrics() {
        // TODO: test TweetPublicMetrics
    }

    /**
     * Test the property 'likeCount'
     */
    @Test
    public void likeCountTest() {
        // TODO: test likeCount
    }

    /**
     * Test the property 'quoteCount'
     */
    @Test
    public void quoteCountTest() {
        // TODO: test quoteCount
    }

    /**
     * Test the property 'replyCount'
     */
    @Test
    public void replyCountTest() {
        // TODO: test replyCount
    }

    /**
     * Test the property 'retweetCount'
     */
    @Test
    public void retweetCountTest() {
        // TODO: test retweetCount
    }

}
