/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetEditControls
 */
public class TweetEditControlsTest {
    private final TweetEditControls model = new TweetEditControls();

    /**
     * Model tests for TweetEditControls
     */
    @Test
    public void testTweetEditControls() {
        // TODO: test TweetEditControls
    }

    /**
     * Test the property 'editableUntil'
     */
    @Test
    public void editableUntilTest() {
        // TODO: test editableUntil
    }

    /**
     * Test the property 'editsRemaining'
     */
    @Test
    public void editsRemainingTest() {
        // TODO: test editsRemaining
    }

    /**
     * Test the property 'isEditEligible'
     */
    @Test
    public void isEditEligibleTest() {
        // TODO: test isEditEligible
    }

}
