/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.TweetNotice;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetNoticeSchema
 */
public class TweetNoticeSchemaTest {
    private final TweetNoticeSchema model = new TweetNoticeSchema();

    /**
     * Model tests for TweetNoticeSchema
     */
    @Test
    public void testTweetNoticeSchema() {
        // TODO: test TweetNoticeSchema
    }

    /**
     * Test the property 'publicTweetNotice'
     */
    @Test
    public void publicTweetNoticeTest() {
        // TODO: test publicTweetNotice
    }

}
