/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.TweetComplianceSchemaTweet;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetComplianceSchema
 */
public class TweetComplianceSchemaTest {
    private final TweetComplianceSchema model = new TweetComplianceSchema();

    /**
     * Model tests for TweetComplianceSchema
     */
    @Test
    public void testTweetComplianceSchema() {
        // TODO: test TweetComplianceSchema
    }

    /**
     * Test the property 'eventAt'
     */
    @Test
    public void eventAtTest() {
        // TODO: test eventAt
    }

    /**
     * Test the property 'quoteTweetId'
     */
    @Test
    public void quoteTweetIdTest() {
        // TODO: test quoteTweetId
    }

    /**
     * Test the property 'tweet'
     */
    @Test
    public void tweetTest() {
        // TODO: test tweet
    }

}
