/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserPublicMetrics
 */
public class UserPublicMetricsTest {
    private final UserPublicMetrics model = new UserPublicMetrics();

    /**
     * Model tests for UserPublicMetrics
     */
    @Test
    public void testUserPublicMetrics() {
        // TODO: test UserPublicMetrics
    }

    /**
     * Test the property 'followersCount'
     */
    @Test
    public void followersCountTest() {
        // TODO: test followersCount
    }

    /**
     * Test the property 'followingCount'
     */
    @Test
    public void followingCountTest() {
        // TODO: test followingCount
    }

    /**
     * Test the property 'listedCount'
     */
    @Test
    public void listedCountTest() {
        // TODO: test listedCount
    }

    /**
     * Test the property 'tweetCount'
     */
    @Test
    public void tweetCountTest() {
        // TODO: test tweetCount
    }

}
