/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.UserComplianceSchema;
import org.openapitools.client.model.UserDeleteComplianceSchema;
import org.openapitools.client.model.UserProfileModificationComplianceSchema;
import org.openapitools.client.model.UserProfileModificationObjectSchema;
import org.openapitools.client.model.UserProtectComplianceSchema;
import org.openapitools.client.model.UserScrubGeoObjectSchema;
import org.openapitools.client.model.UserScrubGeoSchema;
import org.openapitools.client.model.UserSuspendComplianceSchema;
import org.openapitools.client.model.UserTakedownComplianceSchema;
import org.openapitools.client.model.UserUndeleteComplianceSchema;
import org.openapitools.client.model.UserUnprotectComplianceSchema;
import org.openapitools.client.model.UserUnsuspendComplianceSchema;
import org.openapitools.client.model.UserWithheldComplianceSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserComplianceData
 */
public class UserComplianceDataTest {
    private final UserComplianceData model = new UserComplianceData();

    /**
     * Model tests for UserComplianceData
     */
    @Test
    public void testUserComplianceData() {
        // TODO: test UserComplianceData
    }

    /**
     * Test the property 'userProtect'
     */
    @Test
    public void userProtectTest() {
        // TODO: test userProtect
    }

    /**
     * Test the property 'userUnprotect'
     */
    @Test
    public void userUnprotectTest() {
        // TODO: test userUnprotect
    }

    /**
     * Test the property 'userDelete'
     */
    @Test
    public void userDeleteTest() {
        // TODO: test userDelete
    }

    /**
     * Test the property 'userUndelete'
     */
    @Test
    public void userUndeleteTest() {
        // TODO: test userUndelete
    }

    /**
     * Test the property 'userSuspend'
     */
    @Test
    public void userSuspendTest() {
        // TODO: test userSuspend
    }

    /**
     * Test the property 'userUnsuspend'
     */
    @Test
    public void userUnsuspendTest() {
        // TODO: test userUnsuspend
    }

    /**
     * Test the property 'userWithheld'
     */
    @Test
    public void userWithheldTest() {
        // TODO: test userWithheld
    }

    /**
     * Test the property 'scrubGeo'
     */
    @Test
    public void scrubGeoTest() {
        // TODO: test scrubGeo
    }

    /**
     * Test the property 'userProfileModification'
     */
    @Test
    public void userProfileModificationTest() {
        // TODO: test userProfileModification
    }

}
