openapi: 3.0.0
info:
  contact:
    name: Twitter Developers
    url: https://developer.twitter.com/
  description: Twitter API v2 available endpoints
  license:
    name: Twitter Developer Agreement and Policy
    url: https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
  termsOfService: https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
  title: Twitter API v2
  version: "2.54"
servers:
- description: Twitter API
  url: https://api.twitter.com
tags:
- description: "Endpoints related to retrieving, managing bookmarks of a user"
  name: Bookmarks
- description: Endpoints related to keeping Twitter data in your systems compliant
  name: Compliance
- description: Miscellaneous endpoints for general API functionality
  name: General
- description: "Endpoints related to retrieving, managing Lists"
  name: Lists
- description: "Endpoints related to retrieving, managing Spaces"
  name: Spaces
- description: "Endpoints related to retrieving, searching, and modifying Tweets"
  name: Tweets
- description: "Endpoints related to retrieving, managing relationships of Users"
  name: Users
paths:
  /2/compliance/jobs:
    get:
      description: Returns recent Compliance Jobs for a given job type and optional
        job status
      operationId: listBatchComplianceJobs
      security:
      - BearerToken: []
      summary: List Compliance Jobs
      tags:
      - Compliance
      x-accepts: application/json
    post:
      description: Creates a compliance for the given job type
      operationId: createBatchComplianceJob
      security:
      - BearerToken: []
      summary: Create compliance job
      tags:
      - Compliance
      x-content-type: application/json
      x-accepts: application/json
  /2/compliance/jobs/{id}:
    get:
      description: Returns a single Compliance Job by ID
      operationId: getBatchComplianceJob
      security:
      - BearerToken: []
      summary: Get Compliance Job
      tags:
      - Compliance
      x-accepts: application/json
  /2/lists:
    post:
      description: Creates a new List.
      operationId: listIdCreate
      security:
      - OAuth2UserToken:
        - list.read
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Create List
      tags:
      - Lists
      x-content-type: application/json
      x-accepts: application/json
  /2/lists/{id}:
    delete:
      description: Delete a List that you own.
      operationId: listIdDelete
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Delete List
      tags:
      - Lists
      x-accepts: application/json
    get:
      description: Returns a List.
      operationId: listIdGet
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: List lookup by List ID.
      tags:
      - Lists
      x-accepts: application/json
    put:
      description: Update a List that you own.
      operationId: listIdUpdate
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Update List.
      tags:
      - Lists
      x-content-type: application/json
      x-accepts: application/json
  /2/lists/{id}/followers:
    get:
      description: Returns a list of Users that follow a List by the provided List
        ID
      operationId: listGetFollowers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that follow a List by the provided List ID
      tags:
      - Users
      x-accepts: application/json
  /2/lists/{id}/members:
    get:
      description: Returns a list of Users that are members of a List by the provided
        List ID.
      operationId: listGetMembers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are members of a List by the provided List
        ID.
      tags:
      - Users
      x-accepts: application/json
    post:
      description: Causes a User to become a member of a List.
      operationId: listAddMember
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Add a List member
      tags:
      - Lists
      x-content-type: application/json
      x-accepts: application/json
  /2/lists/{id}/members/{user_id}:
    delete:
      description: Causes a User to be removed from the members of a List.
      operationId: listRemoveMember
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Remove a List member
      tags:
      - Lists
      x-accepts: application/json
  /2/lists/{id}/tweets:
    get:
      description: Returns a list of Tweets associated with the provided List ID.
      operationId: listsIdTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: List Tweets timeline by List ID.
      tags:
      - Tweets
      x-accepts: application/json
  /2/openapi.json:
    get:
      description: Full OpenAPI Specification in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)
      operationId: getOpenApiSpec
      summary: Returns the OpenAPI Specification document.
      tags:
      - General
      x-accepts: application/json
  /2/spaces:
    get:
      description: Returns a variety of information about the Spaces specified by
        the requested IDs
      operationId: findSpacesByIds
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup up Space IDs
      tags:
      - Spaces
      x-accepts: application/json
  /2/spaces/by/creator_ids:
    get:
      description: Returns a variety of information about the Spaces created by the
        provided User IDs
      operationId: findSpacesByCreatorIds
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup by their creators
      tags:
      - Spaces
      x-accepts: application/json
  /2/spaces/search:
    get:
      description: Returns Spaces that match the provided query.
      operationId: searchSpaces
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Search for Spaces
      tags:
      - Spaces
      x-accepts: application/json
  /2/spaces/{id}:
    get:
      description: Returns a variety of information about the Space specified by the
        requested ID
      operationId: findSpaceById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup by Space ID
      tags:
      - Spaces
      x-accepts: application/json
  /2/spaces/{id}/buyers:
    get:
      description: Retrieves the list of Users who purchased a ticket to the given
        space
      operationId: spaceBuyers
      security:
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Retrieve the list of Users who purchased a ticket to the given space
      tags:
      - Spaces
      - Tweets
      x-accepts: application/json
  /2/spaces/{id}/tweets:
    get:
      description: Retrieves Tweets shared in the specified Space.
      operationId: spaceTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Retrieve Tweets from a Space.
      tags:
      - Spaces
      - Tweets
      x-accepts: application/json
  /2/tweets:
    get:
      description: Returns a variety of information about the Tweet specified by the
        requested ID.
      operationId: findTweetsById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Tweet lookup by Tweet IDs
      tags:
      - Tweets
      x-accepts: application/json
    post:
      description: Causes the User to create a Tweet under the authorized account.
      operationId: createTweet
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Creation of a Tweet
      tags:
      - Tweets
      x-content-type: application/json
      x-accepts: application/json
  /2/tweets/compliance/stream:
    get:
      description: Streams 100% of compliance data for Tweets
      operationId: getTweetsComplianceStream
      security:
      - BearerToken: []
      summary: Tweets Compliance stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-accepts: application/json
  /2/tweets/counts/all:
    get:
      description: Returns Tweet Counts that match a search query.
      operationId: tweetCountsFullArchiveSearch
      security:
      - BearerToken: []
      summary: Full archive search counts
      tags:
      - Tweets
      x-accepts: application/json
  /2/tweets/counts/recent:
    get:
      description: Returns Tweet Counts from the last 7 days that match a search query.
      operationId: tweetCountsRecentSearch
      security:
      - BearerToken: []
      summary: Recent search counts
      tags:
      - Tweets
      x-accepts: application/json
  /2/tweets/firehose/stream:
    get:
      description: Streams 100% of public Tweets.
      operationId: getTweetsFirehoseStream
      security:
      - BearerToken: []
      summary: Firehose stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-accepts: application/json
  /2/tweets/label/stream:
    get:
      description: Streams 100% of labeling events applied to Tweets
      operationId: getTweetsLabelStream
      security:
      - BearerToken: []
      summary: Tweets Label stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-accepts: application/json
  /2/tweets/sample/stream:
    get:
      description: Streams a deterministic 1% of public Tweets.
      operationId: sampleStream
      security:
      - BearerToken: []
      summary: Sample stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-accepts: application/json
  /2/tweets/sample10/stream:
    get:
      description: Streams a deterministic 10% of public Tweets.
      operationId: getTweetsSample10Stream
      security:
      - BearerToken: []
      summary: Sample 10% stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-accepts: application/json
  /2/tweets/search/all:
    get:
      description: Returns Tweets that match a search query.
      operationId: tweetsFullarchiveSearch
      security:
      - BearerToken: []
      summary: Full-archive search
      tags:
      - Tweets
      x-accepts: application/json
  /2/tweets/search/recent:
    get:
      description: Returns Tweets from the last 7 days that match a search query.
      operationId: tweetsRecentSearch
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Recent search
      tags:
      - Tweets
      x-accepts: application/json
  /2/tweets/search/stream:
    get:
      description: Streams Tweets matching the stream's active rule set.
      operationId: searchStream
      security:
      - BearerToken: []
      summary: Filtered stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-accepts: application/json
  /2/tweets/search/stream/rules:
    get:
      description: "Returns rules from a User's active rule set. Users can fetch all\
        \ of their rules or a subset, specified by the provided rule ids."
      operationId: getRules
      security:
      - BearerToken: []
      summary: Rules lookup
      tags:
      - Tweets
      x-accepts: application/json
    post:
      description: "Add or delete rules from a User's active rule set. Users can provide\
        \ unique, optionally tagged rules to add. Users can delete their entire rule\
        \ set or a subset specified by rule ids or values."
      operationId: addOrDeleteRules
      security:
      - BearerToken: []
      summary: Add/Delete rules
      tags:
      - Tweets
      x-content-type: application/json
      x-accepts: application/json
  /2/tweets/{id}:
    delete:
      description: Delete specified Tweet (in the path) by ID.
      operationId: deleteTweetById
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Tweet delete by Tweet ID
      tags:
      - Tweets
      x-accepts: application/json
    get:
      description: Returns a variety of information about the Tweet specified by the
        requested ID.
      operationId: findTweetById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Tweet lookup by Tweet ID
      tags:
      - Tweets
      x-accepts: application/json
  /2/tweets/{id}/liking_users:
    get:
      description: Returns a list of Users that have liked the provided Tweet ID
      operationId: tweetsIdLikingUsers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - like.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that have liked the provided Tweet ID
      tags:
      - Users
      x-accepts: application/json
  /2/tweets/{id}/quote_tweets:
    get:
      description: Returns a variety of information about each Tweet that quotes the
        Tweet specified by the requested ID.
      operationId: findTweetsThatQuoteATweet
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Retrieve Tweets that quote a Tweet.
      tags:
      - Tweets
      x-accepts: application/json
  /2/tweets/{id}/retweeted_by:
    get:
      description: Returns a list of Users that have retweeted the provided Tweet
        ID
      operationId: tweetsIdRetweetingUsers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that have retweeted the provided Tweet ID
      tags:
      - Users
      x-accepts: application/json
  /2/tweets/{tweet_id}/hidden:
    put:
      description: Hides or unhides a reply to an owned conversation.
      operationId: hideReplyById
      security:
      - OAuth2UserToken:
        - tweet.moderate.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Hide replies
      tags:
      - Tweets
      x-content-type: application/json
      x-accepts: application/json
  /2/users:
    get:
      description: This endpoint returns information about Users. Specify Users by
        their ID.
      operationId: findUsersById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by IDs
      tags:
      - Users
      x-accepts: application/json
  /2/users/by:
    get:
      description: This endpoint returns information about Users. Specify Users by
        their username.
      operationId: findUsersByUsername
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by usernames
      tags:
      - Users
      x-accepts: application/json
  /2/users/by/username/{username}:
    get:
      description: This endpoint returns information about a User. Specify User by
        username.
      operationId: findUserByUsername
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by username
      tags:
      - Users
      x-accepts: application/json
  /2/users/compliance/stream:
    get:
      description: Streams 100% of compliance data for Users
      operationId: getUsersComplianceStream
      security:
      - BearerToken: []
      summary: Users Compliance stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-accepts: application/json
  /2/users/me:
    get:
      description: This endpoint returns information about the requesting User.
      operationId: findMyUser
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup me
      tags:
      - Users
      x-accepts: application/json
  /2/users/{id}:
    get:
      description: This endpoint returns information about a User. Specify User by
        ID.
      operationId: findUserById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by ID
      tags:
      - Users
      x-accepts: application/json
  /2/users/{id}/blocking:
    get:
      description: Returns a list of Users that are blocked by the provided User ID
      operationId: usersIdBlocking
      security:
      - OAuth2UserToken:
        - block.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are blocked by provided User ID
      tags:
      - Users
      x-accepts: application/json
    post:
      description: Causes the User (in the path) to block the target User. The User
        (in the path) must match the User context authorizing the request
      operationId: usersIdBlock
      security:
      - OAuth2UserToken:
        - block.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Block User by User ID
      tags:
      - Users
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/bookmarks:
    get:
      description: Returns Tweet objects that have been bookmarked by the requesting
        User
      operationId: getUsersIdBookmarks
      security:
      - OAuth2UserToken:
        - bookmark.read
        - tweet.read
        - users.read
      summary: Bookmarks by User
      tags:
      - Bookmarks
      x-accepts: application/json
    post:
      description: Adds a Tweet (ID in the body) to the requesting User's (in the
        path) bookmarks
      operationId: postUsersIdBookmarks
      security:
      - OAuth2UserToken:
        - bookmark.write
        - tweet.read
        - users.read
      summary: Add Tweet to Bookmarks
      tags:
      - Bookmarks
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/bookmarks/{tweet_id}:
    delete:
      description: Removes a Tweet from the requesting User's bookmarked Tweets.
      operationId: usersIdBookmarksDelete
      security:
      - OAuth2UserToken:
        - bookmark.write
        - tweet.read
        - users.read
      summary: Remove a bookmarked Tweet
      tags:
      - Bookmarks
      x-accepts: application/json
  /2/users/{id}/followed_lists:
    get:
      description: Returns a User's followed Lists.
      operationId: userFollowedLists
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get User's Followed Lists
      tags:
      - Lists
      x-accepts: application/json
    post:
      description: Causes a User to follow a List.
      operationId: listUserFollow
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Follow a List
      tags:
      - Lists
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/followed_lists/{list_id}:
    delete:
      description: Causes a User to unfollow a List.
      operationId: listUserUnfollow
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unfollow a List
      tags:
      - Lists
      x-accepts: application/json
  /2/users/{id}/followers:
    get:
      description: Returns a list of Users who are followers of the specified User
        ID.
      operationId: usersIdFollowers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - follows.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Followers by User ID
      tags:
      - Users
      x-accepts: application/json
  /2/users/{id}/following:
    get:
      description: Returns a list of Users that are being followed by the provided
        User ID
      operationId: usersIdFollowing
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - follows.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Following by User ID
      tags:
      - Users
      x-accepts: application/json
    post:
      description: "Causes the User(in the path) to follow, or “request to follow”\
        \ for protected Users, the target User. The User(in the path) must match the\
        \ User context authorizing the request"
      operationId: usersIdFollow
      security:
      - OAuth2UserToken:
        - follows.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Follow User
      tags:
      - Users
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/liked_tweets:
    get:
      description: Returns a list of Tweets liked by the provided User ID
      operationId: usersIdLikedTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - like.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns Tweet objects liked by the provided User ID
      tags:
      - Tweets
      x-accepts: application/json
  /2/users/{id}/likes:
    post:
      description: Causes the User (in the path) to like the specified Tweet. The
        User in the path must match the User context authorizing the request.
      operationId: usersIdLike
      security:
      - OAuth2UserToken:
        - like.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to like the specified Tweet
      tags:
      - Tweets
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/likes/{tweet_id}:
    delete:
      description: Causes the User (in the path) to unlike the specified Tweet. The
        User must match the User context authorizing the request
      operationId: usersIdUnlike
      security:
      - OAuth2UserToken:
        - like.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to unlike the specified Tweet
      tags:
      - Tweets
      x-accepts: application/json
  /2/users/{id}/list_memberships:
    get:
      description: Get a User's List Memberships.
      operationId: getUserListMemberships
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's List Memberships
      tags:
      - Lists
      x-accepts: application/json
  /2/users/{id}/mentions:
    get:
      description: Returns Tweet objects that mention username associated to the provided
        User ID
      operationId: usersIdMentions
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User mention timeline by User ID
      tags:
      - Tweets
      x-accepts: application/json
  /2/users/{id}/muting:
    get:
      description: Returns a list of Users that are muted by the provided User ID
      operationId: usersIdMuting
      security:
      - OAuth2UserToken:
        - mute.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are muted by the provided User ID
      tags:
      - Users
      x-accepts: application/json
    post:
      description: Causes the User (in the path) to mute the target User. The User
        (in the path) must match the User context authorizing the request.
      operationId: usersIdMute
      security:
      - OAuth2UserToken:
        - mute.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Mute User by User ID.
      tags:
      - Users
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/owned_lists:
    get:
      description: Get a User's Owned Lists.
      operationId: listUserOwnedLists
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's Owned Lists.
      tags:
      - Lists
      x-accepts: application/json
  /2/users/{id}/pinned_lists:
    get:
      description: Get a User's Pinned Lists.
      operationId: listUserPinnedLists
      security:
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's Pinned Lists
      tags:
      - Lists
      x-accepts: application/json
    post:
      description: Causes a User to pin a List.
      operationId: listUserPin
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Pin a List
      tags:
      - Lists
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/pinned_lists/{list_id}:
    delete:
      description: Causes a User to remove a pinned List.
      operationId: listUserUnpin
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unpin a List
      tags:
      - Lists
      x-accepts: application/json
  /2/users/{id}/retweets:
    post:
      description: Causes the User (in the path) to retweet the specified Tweet. The
        User in the path must match the User context authorizing the request.
      operationId: usersIdRetweets
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to retweet the specified Tweet.
      tags:
      - Tweets
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/retweets/{source_tweet_id}:
    delete:
      description: Causes the User (in the path) to unretweet the specified Tweet.
        The User must match the User context authorizing the request
      operationId: usersIdUnretweets
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to unretweet the specified Tweet
      tags:
      - Tweets
      x-accepts: application/json
  /2/users/{id}/timelines/reverse_chronological:
    get:
      description: Returns Tweet objects that appears in the provided User ID's home
        timeline
      operationId: usersIdTimeline
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User home timeline by User ID
      tags:
      - Tweets
      x-accepts: application/json
  /2/users/{id}/tweets:
    get:
      description: Returns a list of Tweets authored by the provided User ID
      operationId: usersIdTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User Tweets timeline by User ID
      tags:
      - Tweets
      x-accepts: application/json
  /2/users/{source_user_id}/blocking/{target_user_id}:
    delete:
      description: Causes the source User to unblock the target User. The source User
        must match the User context authorizing the request
      operationId: usersIdUnblock
      security:
      - OAuth2UserToken:
        - block.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unblock User by User ID
      tags:
      - Users
      x-accepts: application/json
  /2/users/{source_user_id}/following/{target_user_id}:
    delete:
      description: Causes the source User to unfollow the target User. The source
        User must match the User context authorizing the request
      operationId: usersIdUnfollow
      security:
      - OAuth2UserToken:
        - follows.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unfollow User
      tags:
      - Users
      x-accepts: application/json
  /2/users/{source_user_id}/muting/{target_user_id}:
    delete:
      description: Causes the source User to unmute the target User. The source User
        must match the User context authorizing the request
      operationId: usersIdUnmute
      security:
      - OAuth2UserToken:
        - mute.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unmute User by User ID
      tags:
      - Users
      x-accepts: application/json
components:
  securitySchemes:
    BearerToken:
      scheme: bearer
      type: http
    OAuth2UserToken:
      flows:
        authorizationCode:
          authorizationUrl: https://api.twitter.com/2/oauth2/authorize
          scopes:
            block.read: Accounts you’ve blocked.
            block.write: Block and unblock accounts for you.
            bookmark.read: Allows an app to read bookmarked Tweets
            bookmark.write: Allows an app to create and delete bookmarks
            follows.read: People who follow you and people who you follow.
            follows.write: Follow and unfollow people for you.
            like.read: Tweets you’ve liked and likes you can view.
            like.write: Like and un-like Tweets for you.
            list.read: "Lists, list members, and list followers of lists you’ve created\
              \ or are a member of, including private lists."
            list.write: Create and manage Lists for you.
            mute.read: Accounts you’ve muted.
            mute.write: Mute and unmute accounts for you.
            offline.access: App can request refresh token.
            space.read: Access all of the Spaces you can see.
            tweet.moderate.write: Hide and unhide replies to your Tweets.
            tweet.read: "All the Tweets you can see, including Tweets from protected\
              \ accounts."
            tweet.write: Tweet and retweet for you.
            users.read: "Any account you can see, including protected accounts. Any\
              \ account you can see, including protected accounts."
          tokenUrl: https://api.twitter.com/2/oauth2/token
      type: oauth2
    UserToken:
      scheme: OAuth
      type: http

